name: Matrix Deployment
on: push
jobs: 
  build:
    continue-on-error: true
    strategy:
      matrix:
        os-version: [ubuntu-latest, windows-latest]
        node-version: [16, 18, 20]
        exclude:
          - os-version: windows-latest
            node-version: 16
    runs-on: ${{ matrix.os-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build    
